// SPDX-FileCopyrightText: 2026 Erin Catto
// SPDX-FileCopyrightText: 2026 Ikpil Choi(ikpil@naver.com)
// SPDX-License-Identifier: MIT

namespace Box2D.NET
{
    // Generated by CMake from build_hash.h.in. Do not edit.
    // Short git hash stamped into each recording so replay can refuse a file made
    // by a different engine build. Resolved at configure time, so it can lag the
    // working tree by a commit until the next cmake run. 0 means unstamped (no git
    // available, or a recording made before stamping existed) and skips the check.
    // The managed value is generated by MSBuild rather than CMake.
    internal static class B2BuildHash
    {
        internal const uint Value = (uint)B2BuildHashGenerated.Value;
    }
}
